# Generated by Django 6.0.6 on 2026-06-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('specialization', models.CharField(max_length=100)),
                ('experience_years', models.IntegerField()),
                ('available_days', models.CharField(max_length=200)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('profile_image', models.ImageField(blank=True, upload_to='doctors/')),
            ],
        ),
    ]
